package br.com.munif.stella.api.dto;

import java.util.UUID;

/**
 * Full response DTO of a main item.
 *
 * <p>Returned in create, update, and individual query operations.
 * Includes all fields of the main item, with complete image metadata
 * for display and for authorship verification (AI-generated or not).</p>
 *
 * @param id                   unique identifier of the main item
 * @param nome                 main item name
 * @param descricao            detailed description; may be {@code null}
 * @param observacoes          internal notes; may be {@code null}
 * @param origemCadastro       registration origin (e.g.: {@code "MANUAL"}, {@code "IA"}); may be {@code null}
 * @param categoriaId          category identifier; may be {@code null}
 * @param categoriaNome        category name (denormalized); may be {@code null}
 * @param categoriaIcone       category icon key; may be {@code null}
 * @param imagemUrl            relative URL for accessing the image; {@code null} when no image
 * @param imagemContentType    image MIME type (e.g.: {@code "image/jpeg"}); may be {@code null}
 * @param imagemTamanhoBytes   image size in bytes; may be {@code null}
 * @param imagemGeneratedByAi  {@code true} if the image was generated by AI
 * @param imagemProvider       identifier of the AI provider that generated the image; may be {@code null}
 * @param ativa                indicates whether the item is active in the system
 */
public record ItemMestreResponseDTO(
        UUID id,
        String nome,
        String descricao,
        String observacoes,
        String origemCadastro,
        UUID categoriaId,
        String categoriaNome,
        String categoriaIcone,
        String imagemUrl,
        String imagemContentType,
        Long imagemTamanhoBytes,
        boolean imagemGeneratedByAi,
        String imagemProvider,
        boolean ativa
) {}
