server:
  port: 8080

spring:
  application:
    name: pagadoria-api

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pagadoria
    username: pagadoria
    password: pagadoria
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${pagadoria.keycloak.base-url}/realms/${pagadoria.keycloak.realm}

pagadoria:
  cors:
    allowed-origins: ${PAGADORIA_CORS_ALLOWED_ORIGINS:http://127.0.0.1:4200}
  keycloak:
    base-url: ${PAGADORIA_KEYCLOAK_BASE_URL:http://127.0.0.1:9080}
    realm: ${PAGADORIA_KEYCLOAK_REALM:pagadoria}
    public-client-id: ${PAGADORIA_KEYCLOAK_PUBLIC_CLIENT_ID:pagadoria-cli}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO

