server:
  port: 8080

spring:
  application:
    name: stella-api

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stella
    username: stella
    password: stella
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${stella.keycloak.base-url}/realms/${stella.keycloak.realm}

stella:
  cors:
    allowed-origins:
      - ${STELLA_CORS_ALLOWED_ORIGIN_1:http://127.0.0.1:4200}
      - ${STELLA_CORS_ALLOWED_ORIGIN_2:http://localhost:4200}
  keycloak:
    base-url: ${STELLA_KEYCLOAK_BASE_URL:http://127.0.0.1:9080}
    realm: ${STELLA_KEYCLOAK_REALM:stella}
    public-client-id: ${STELLA_KEYCLOAK_PUBLIC_CLIENT_ID:stella-cli}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /v3/api-docs

scalar:
  enabled: true
  path: /scalar
  url: /v3/api-docs
  theme: deepSpace
  layout: modern
  darkMode: true
