package br.com.munif.comum.service;

import br.com.munif.comum.dto.RevisaoDTO;
import br.com.munif.comum.persistencia.Entidade;
import br.com.munif.comum.persistencia.SuperRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityNotFoundException;
import org.hibernate.envers.AuditReader;
import org.hibernate.envers.AuditReaderFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Base service with persistence operations common to all entities in the system.
 *
 * <p>Centralizes generic CRUD and revision history queries (Hibernate Envers),
 * eliminating repeated code in concrete services.
 * Each concrete service inherits from this class, providing the entity type ({@code T})
 * and the corresponding repository ({@code R}).</p>
 *
 * <p><strong>Soft deletion:</strong> the {@link #excluir(UUID)} method does not remove the
 * record from the database; it only sets {@code ativo = false} via
 * {@link Entidade#excluirLogicamente()}.</p>
 *
 * <p><strong>History:</strong> {@link #listarVersoesAnteriores(UUID)} returns audited snapshots
 * generated by Hibernate Envers, excluding the current revision (which represents the
 * present state, already accessible via {@link #buscarPorId(UUID)}).</p>
 *
 * @param <T> type of the managed entity
 * @param <R> type of the repository, which must extend {@link SuperRepository}
 */
public abstract class SuperService<T extends Entidade, R extends SuperRepository<T>> {

    /** Spring Data repository of the managed entity, available to subclasses. */
    protected final R repository;

    /**
     * JPA {@code EntityManager}, required to obtain the Envers {@link AuditReader}.
     * Available to subclasses that need advanced JPA operations.
     */
    protected final EntityManager entityManager;

    /** Entity class, used for Envers queries with the generic {@code find} method. */
    private final Class<T> entityClass;

    /**
     * Constructor required by subclasses to inject the fundamental dependencies.
     *
     * @param repository   entity repository
     * @param entityManager JPA entity manager
     * @param entityClass   literal class of the entity (e.g.: {@code ItemMestre.class})
     */
    protected SuperService(R repository, EntityManager entityManager, Class<T> entityClass) {
        this.repository = repository;
        this.entityManager = entityManager;
        this.entityClass = entityClass;
    }

    /**
     * Persists or updates an entity.
     *
     * @param entidade entity to save
     * @return saved entity, with database-generated fields (e.g.: {@code id}, {@code version})
     */
    public T salvar(T entidade) {
        return repository.save(entidade);
    }

    /**
     * Returns all active records of the entity.
     *
     * @return list of active entities, ordering defined by the concrete repository
     */
    public List<T> listarTodos() {
        return repository.findAll();
    }

    /**
     * Returns all records of the entity, including logically deactivated ones.
     *
     * @return complete list, regardless of the {@code ativo} field
     */
    public List<T> listarTodosIncluindoInativos() {
        return repository.listarTodosIncluindoInativos();
    }

    /**
     * Finds a record by its unique identifier.
     *
     * @param id UUID identifier of the record
     * @return entity found
     * @throws EntityNotFoundException if no record exists with the given {@code id}
     */
    public T buscarPorId(UUID id) {
        return repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Record not found for id: " + id));
    }

    /**
     * Performs the soft deletion of the record identified by {@code id}.
     *
     * <p>The record remains in the database with {@code ativo = false}
     * and will not appear in standard listings.</p>
     *
     * @param id identifier of the record to deactivate
     * @throws EntityNotFoundException if the record does not exist
     */
    public void excluir(UUID id) {
        T entidade = buscarPorId(id);
        entidade.excluirLogicamente();
        repository.save(entidade);
    }

    /**
     * Returns the previous revisions of a record, excluding the current revision.
     *
     * <p>Uses Hibernate Envers to query the audited history.
     * Each item in the list represents a snapshot of the entity state at
     * a past moment.</p>
     *
     * @param id identifier of the record whose history is to be queried
     * @return list of revisions in ascending order of revision number;
     *         empty list if there is no history
     */
    public List<RevisaoDTO<T>> listarVersoesAnteriores(UUID id) {
        AuditReader auditReader = AuditReaderFactory.get(entityManager);
        List<Number> revisoes = auditReader.getRevisions(entityClass, id);

        if (revisoes.isEmpty()) {
            return List.of();
        }

        List<RevisaoDTO<T>> resultado = new ArrayList<>();
        // The last revision represents the current state, already obtained by buscarPorId().
        // Therefore we iterate only up to revisoes.size() - 1.
        for (int i = 0; i < revisoes.size() - 1; i++) {
            Number numeroRevisao = revisoes.get(i);
            T entidadeRevisada = auditReader.find(entityClass, id, numeroRevisao);

            if (entidadeRevisada != null) {
                resultado.add(new RevisaoDTO<>(
                        numeroRevisao,
                        auditReader.getRevisionDate(numeroRevisao).toInstant(),
                        entidadeRevisada
                ));
            }
        }

        return resultado;
    }
}
