package br.com.munif.common.dto;

import java.time.Instant;

/**
 * Generic DTO representing an audited revision of an entity.
 *
 * <p>Used to expose the change history tracked by Hibernate Envers.
 * Each instance corresponds to a version of the entity at a specific point in time.
 * The type parameter {@code T} must be the full response DTO of the audited entity.</p>
 *
 * <p>Usage example: {@code RevisionDTO<PersonResponseDTO>} for the change history
 * of a {@code Person}.</p>
 *
 * @param <T>      response DTO type of the audited entity
 * @param revision  sequential revision number generated by Hibernate Envers
 * @param timestamp date and time when the revision was created (UTC)
 * @param entity snapshot of the entity data at this revision, represented as a DTO
 */
public record RevisionDTO<T>(
        Number revision,
        Instant timestamp,
        T entity
) {
}
