package br.com.munif.common.service;

import br.com.munif.common.dto.RevisionDTO;
import br.com.munif.common.persistencia.BaseEntity;
import br.com.munif.common.persistencia.SuperRepository;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityNotFoundException;
import org.hibernate.envers.AuditReader;
import org.hibernate.envers.AuditReaderFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Base service with persistence operations common to all entities in the system.
 *
 * <p>Centralizes generic CRUD and revision history queries (Hibernate Envers),
 * eliminating repeated code in concrete services.
 * Each concrete service inherits from this class, providing the entity type ({@code T})
 * and the corresponding repository ({@code R}).</p>
 *
 * <p><strong>Soft deletion:</strong> the {@link #delete(UUID)} method does not remove the
 * record from the database; it only sets {@code active = false} via
 * {@link BaseEntity#deleteLogically()}.</p>
 *
 * <p><strong>History:</strong> {@link #listPreviousVersions(UUID)} returns audited snapshots
 * generated by Hibernate Envers, excluding the current revision (which represents the
 * present state, already accessible via {@link #findById(UUID)}).</p>
 *
 * @param <T> type of the managed entity
 * @param <R> type of the repository, which must extend {@link SuperRepository}
 */
public abstract class SuperService<T extends BaseEntity, R extends SuperRepository<T>> {

    /** Spring Date repository of the managed entity, available to subclasses. */
    protected final R repository;

    /**
     * JPA {@code EntityManager}, required to obtain the Envers {@link AuditReader}.
     * Available to subclasses that need advanced JPA operations.
     */
    protected final EntityManager entityManager;

    /** Entity class, used for Envers queries with the generic {@code find} method. */
    private final Class<T> entityClass;

    /**
     * Constructor required by subclasses to inject the fundamental dependencies.
     *
     * @param repository   entity repository
     * @param entityManager JPA entity manager
     * @param entityClass   literal class of the entity (e.g.: {@code MainItem.class})
     */
    protected SuperService(R repository, EntityManager entityManager, Class<T> entityClass) {
        this.repository = repository;
        this.entityManager = entityManager;
        this.entityClass = entityClass;
    }

    /**
     * Persists or updates an entity.
     *
     * @param entity entity to save
     * @return saved entity, with database-generated fields (e.g.: {@code id}, {@code version})
     */
    public T save(T entity) {
        return repository.save(entity);
    }

    /**
     * Persists a new entity and applies an explicitly requested inactive state after
     * the initial insert.
     *
     * <p>{@link BaseEntity#prePersist()} always makes a new entity active. When callers
     * request {@code false}, the insert must therefore be flushed before the entity is
     * logically deactivated and saved again. A {@code true} or {@code null} request keeps
     * the default active state and requires only the initial persistence.</p>
     *
     * @param entity entity to persist
     * @param requestedActive requested initial state; only {@code false} triggers deactivation
     * @return persisted entity with the requested state applied
     */
    protected T saveWithRequestedActiveState(T entity, Boolean requestedActive) {
        T saved = save(entity);
        if (!Boolean.FALSE.equals(requestedActive)) {
            return saved;
        }

        repository.flush();
        saved.deleteLogically();
        return save(saved);
    }

    /**
     * Returns all active records of the entity.
     *
     * @return list of active entities, ordering defined by the concrete repository
     */
    public List<T> listAll() {
        return repository.findAll();
    }

    /**
     * Returns all records of the entity, including logically deactivated ones.
     *
     * @return complete list, regardless of the {@code active} field
     */
    public List<T> findAllIncludingInactive() {
        return repository.findAllIncludingInactive();
    }

    /**
     * Finds a record by its unique identifier.
     *
     * @param id UUID identifier of the record
     * @return entity found
     * @throws EntityNotFoundException if no record exists with the given {@code id}
     */
    public T findById(UUID id) {
        return repository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Record not found for id: " + id));
    }

    /**
     * Performs the soft deletion of the record identified by {@code id}.
     *
     * <p>The record remains in the database with {@code active = false}
     * and will not appear in standard listings.</p>
     *
     * @param id identifier of the record to deactivate
     * @throws EntityNotFoundException if the record does not exist
     */
    public void delete(UUID id) {
        T entity = findById(id);
        entity.deleteLogically();
        repository.save(entity);
    }

    /**
     * Returns the previous revisions of a record, excluding the current revision.
     *
     * <p>Uses Hibernate Envers to query the audited history.
     * Each item in the list represents a snapshot of the entity state at
     * a past moment.</p>
     *
     * @param id identifier of the record whose history is to be queried
     * @return list of revisions in ascending order of revision number;
     *         empty list if there is no history
     */
    public List<RevisionDTO<T>> listPreviousVersions(UUID id) {
        findById(id);
        AuditReader auditReader = AuditReaderFactory.get(entityManager);
        List<Number> revisions = auditReader.getRevisions(entityClass, id);

        if (revisions.isEmpty()) {
            return List.of();
        }

        List<RevisionDTO<T>> result = new ArrayList<>();
        // The last revision represents the current state, already obtained by findById().
        // Therefore we iterate only up to revisions.size() - 1.
        for (int i = 0; i < revisions.size() - 1; i++) {
            Number numeroRevisao = revisions.get(i);
            T entidadeRevisada = auditReader.find(entityClass, id, numeroRevisao);

            if (entidadeRevisada != null) {
                result.add(new RevisionDTO<>(
                        numeroRevisao,
                        auditReader.getRevisionDate(numeroRevisao).toInstant(),
                        entidadeRevisada
                ));
            }
        }

        return result;
    }
}
