apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: platform
data:
  init.sql: |
    SELECT 'CREATE DATABASE stella_dev'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'stella_dev')\gexec

    SELECT 'CREATE DATABASE stella_staging'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'stella_staging')\gexec

    SELECT 'CREATE DATABASE stella_prod'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'stella_prod')\gexec

    SELECT 'CREATE DATABASE keycloak'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'keycloak')\gexec






