package br.com.munif.common.persistencia;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Version;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

/**
 * Mapped base class for all persistent entities in the system.
 *
 * <p>Centralizes common infrastructure fields — identity, lifecycle,
 * soft deletion, and concurrency control — so that subclasses
 * focus only on business rules.</p>
 *
 * <h2>Soft deletion</h2>
 * <p>In entity is physically removed from the database.
 * The {@code active} field is used to indicate whether the record is in use
 * ({@code true}) or has been deactivated ({@code false}).
 * To deactivate, call {@link #excluirLogicamente()}.</p>
 *
 * <h2>Concurrency control</h2>
 * <p>The {@code version} field implements the JPA {@code @Version} mechanism,
 * preventing conflicting concurrent updates
 * (optimistic locking).</p>
 */
@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@MappedSuperclass
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier of the entity, automatically generated by the database (UUID v4).
     * Never changed after the record is created.
     */
    @EqualsAndHashCode.Include
    @Id
    @GeneratedValue
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Indicates whether the record is active ({@code true}) or has been logically deactivated ({@code false}).
     * Every entity starts as active. Use {@link #excluirLogicamente()} to deactivate.
     */
    @Column(name = "ativo", nullable = false)
    private boolean active = true;

    /**
     * Instant at which the record was created. Automatically populated in {@link #prePersist()}
     * and never changed.
     */
    @Column(name = "criado_em", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Instant of the last modification to the record. Automatically updated in
     * {@link #prePersist()} and {@link #preUpdate()}.
     */
    @Column(name = "alterado_em", nullable = false)
    private Instant updatedAt;

    /**
     * Record version for optimistic concurrency control (optimistic locking).
     * JPA increments this value on each {@code UPDATE}, preventing two concurrent transactions
     * from silently overwriting each other's changes.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version;

    /**
     * Generic extension field for free-form annotations.
     * Included in the base structure to allow subclasses to store
     * short textual information without requiring a new database migration.
     */
    @Column(name = "extra", length = 200)
    private String extra;

    /**
     * Field reserved for internal use and future extensibility.
     * Present in all tables by inheriting from this superclass.
     */
    @Column(name = "oi", length = 100)
    private String oi;

    /**
     * JPA callback executed immediately before the first persistence of the record.
     *
     * <p>Responsibilities:</p>
     * <ul>
     *   <li>Set the {@code createdAt} and {@code updatedAt} instants.</li>
     *   <li>Ensure the entity always starts in the active state — even if the
     *       caller changed the {@code active} field before calling {@code save()},
     *       because deactivation must occur in a dedicated operation after creation.</li>
     * </ul>
     */
    @PrePersist
    public void prePersist() {
        Instant agora = Instant.now();
        this.createdAt = agora;
        this.updatedAt = agora;
        // Ensures active state on creation; deactivation is done after the initial persistence.
        this.active = true;
    }

    /**
     * JPA callback executed immediately before each update of the record.
     * Keeps {@code updatedAt} synchronized with the actual instant of the modification.
     */
    @PreUpdate
    public void preUpdate() {
        this.updatedAt = Instant.now();
    }

    /**
     * Returns {@code true} when the entity has not yet been persisted (no {@code id} assigned).
     *
     * @return {@code true} if the record is new; {@code false} if it already exists in the database.
     */
    public boolean isNova() {
        return this.id == null;
    }

    /**
     * Logically deactivates the record, setting {@code active = false}.
     * The record remains in the database and can be retrieved by queries
     * that include inactive records, but does not appear in standard listings.
     */
    public void excluirLogicamente() {
        this.active = false;
    }

    /**
     * Reactivates a previously deactivated record, setting {@code active = true}.
     */
    public void reativar() {
        this.active = true;
    }
}
