package br.com.munif.common.persistencia;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.envers.RevisionEntity;
import org.hibernate.envers.RevisionNumber;
import org.hibernate.envers.RevisionTimestamp;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;

/**
 * Custom revision entity for Hibernate Envers.
 *
 * <p>Each time an audited record (annotated with {@code @Audited}) is created,
 * updated, or deleted, Envers inserts a row into this table ({@code revision})
 * representing that point in time. The audit tables ({@code _aud})
 * reference this revision via the {@code rev} column.</p>
 *
 * <p>The {@code ip} and {@code username} fields are populated by
 * {@link MRevisionEntityListener} before each new revision.</p>
 *
 * @see MRevisionEntityListener
 */
@Getter
@Setter
@Entity
@Table(name = "revision")
@RevisionEntity(MRevisionEntityListener.class)
public class MRevisionEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Sequential revision number, generated by the database.
     * Used as a foreign key in the audit tables ({@code _aud}).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @RevisionNumber
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    /**
     * Exact instant at which the revision was recorded.
     * Automatically populated by Envers.
     */
    @RevisionTimestamp
    @Column(name = "timestamp", nullable = false)
    private Instant timestamp;

    /**
     * IP address of the client that originated the audited operation.
     * Populated by {@link MRevisionEntityListener}.
     */
    @Column(name = "ip", length = 45)
    private String ip;

    /**
     * Login of the user responsible for the audited change.
     * Populated by {@link MRevisionEntityListener}.
     */
    @Column(name = "username", length = 100)
    private String username;

    /**
     * Canonical email of the authenticated user that produced the revision.
     */
    @Column(name = "owner_email", length = 150)
    private String ownerEmail;

    /**
     * Issuer of the authenticated user that produced the revision.
     */
    @Column(name = "owner_issuer", length = 300)
    private String ownerIssuer;

    /**
     * Field reserved for future extensibility.
     */
    @Column(name = "external_id", length = 100)
    private String externalId;
}
