package br.com.stella.api.dto;

import java.util.List;

/**
 * DTO with the consolidated data displayed on the control panel (dashboard).
 *
 * <p>Aggregates global inventory counters and rankings of locations and categories,
 * allowing a quick view of the system status on the home screen.</p>
 *
 * @param peopleCount               total registered and active persons
 * @param mainItemCount           total registered and active main items
 * @param instanceCount            total registered and active item instances
 * @param availableInstanceCount instances with status {@code DISPONIVEL}
 * @param loanedInstanceCount instances with status {@code EMPRESTADO} (open loans)
 * @param locationCount                total active storage locations
 * @param itemsWithoutImageCount        active main items that do not yet have a registered image
 * @param aiRegisteredItemCount main items whose images were generated by artificial intelligence
 * @param vectorQueryCount    total semantic queries (vector search) performed in the system
 * @param topLocations              ranking of locations with the highest number of stored instances
 * @param topCategories          ranking of categories with the highest number of main items
 */
public record DashboardSummaryDTO(
        long peopleCount,
        long mainItemCount,
        long instanceCount,
        long availableInstanceCount,
        long loanedInstanceCount,
        long locationCount,
        long itemsWithoutImageCount,
        long aiRegisteredItemCount,
        long vectorQueryCount,
        List<DashboardLocationQuantityDTO> topLocations,
        List<DashboardCategoryQuantityDTO> topCategories
) {
}
