package br.com.stella.api.dto;

import java.util.List;

/**
 * DTO with the consolidated data displayed on the control panel (dashboard).
 *
 * <p>Aggregates global inventory counters and rankings of locations and categories,
 * allowing a quick view of the system status on the home screen.</p>
 *
 * @param quantidadePessoas               total registered and active persons
 * @param quantidadeItensMestre           total registered and active main items
 * @param quantidadeInstancias            total registered and active item instances
 * @param quantidadeInstanciasDisponiveis instances with status {@code DISPONIVEL}
 * @param quantidadeInstanciasEmprestadas instances with status {@code EMPRESTADO} (open loans)
 * @param quantidadeLocais                total active storage locations
 * @param quantidadeItensSemImagem        active main items that do not yet have a registered image
 * @param quantidadeItensCadastradosPorIa main items whose images were generated by artificial intelligence
 * @param quantidadeConsultasVetoriais    total semantic queries (vector search) performed in the system
 * @param locaisComMaisItens              ranking of locations with the highest number of stored instances
 * @param categoriasComMaisItens          ranking of categories with the highest number of main items
 */
public record DashboardSummaryDTO(
        long quantidadePessoas,
        long quantidadeItensMestre,
        long quantidadeInstancias,
        long quantidadeInstanciasDisponiveis,
        long quantidadeInstanciasEmprestadas,
        long quantidadeLocais,
        long quantidadeItensSemImagem,
        long quantidadeItensCadastradosPorIa,
        long quantidadeConsultasVetoriais,
        List<DashboardLocalQuantidadeDTO> locaisComMaisItens,
        List<DashboardCategoriaQuantidadeDTO> categoriasComMaisItens
) {
}
