package br.com.stella.api.dto;

import java.util.UUID;

/**
 * Full response DTO of a main item.
 *
 * <p>Returned in create, update, and individual query operations.
 * Includes all fields of the main item, with complete image metadata
 * for display and for authorship verification (AI-generated or not).</p>
 *
 * @param id                   unique identifier of the main item
 * @param name                 main item name
 * @param description            detailed description; may be {@code null}
 * @param notes          internal notes; may be {@code null}
 * @param registrationOrigin       registration origin (e.g.: {@code "MANUAL"}, {@code "IA"}); may be {@code null}
 * @param categoryId          category identifier; may be {@code null}
 * @param categoryName        category name (denormalized); may be {@code null}
 * @param categoryIcon       category icon key; may be {@code null}
 * @param imageUrl            relative URL for accessing the image; {@code null} when no image
 * @param imageContentType    image MIME type (e.g.: {@code "image/jpeg"}); may be {@code null}
 * @param imageSizeBytes   image size in bytes; may be {@code null}
 * @param imageGeneratedByAi  {@code true} if the image was generated by AI
 * @param imageProvider       identifier of the AI provider that generated the image; may be {@code null}
 * @param active                indicates whether the item is active in the system
 */
public record MainItemResponseDTO(
        UUID id,
        String name,
        String description,
        String notes,
        String registrationOrigin,
        UUID categoryId,
        String categoryName,
        String categoryIcon,
        String imageUrl,
        String imageContentType,
        Long imageSizeBytes,
        boolean imageGeneratedByAi,
        String imageProvider,
        boolean active
) {}
