package br.com.stella.api.dto;

import java.time.Instant;
import java.util.List;

/**
 * DTO representing an audited revision of a person.
 *
 * <p>Used to expose the change history tracked by Hibernate Envers.
 * Each instance of this DTO corresponds to a version of the {@code Person} entity
 * at a specific point in time.</p>
 *
 * @param revision         sequential revision number generated by Hibernate Envers
 * @param timestamp        date and time when the revision was created (UTC)
 * @param type            type of the operation that generated the revision (e.g.: {@code "ADD"}, {@code "MOD"}, {@code "DEL"})
 * @param person          snapshot of the person's data at this revision
 * @param changedFields list of field names that were modified in this revision;
 *                        empty on creation (ADD), since all fields are new
 */
public record PersonRevisionDTO(
        Number revision,
        Instant timestamp,
        String type,
        PersonResponseDTO person,
        List<String> changedFields
) {
}
