package br.com.munif.stella.api.controller;

import br.com.munif.stella.api.dto.CadastroFotoSugestaoResponseDTO;
import br.com.munif.stella.api.service.CadastroFotoIaService;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

/**
 * REST controller for the AI-assisted photo registration flow.
 *
 * <p>Exposes the {@code /api/v0/ia/cadastro-foto} resource. Receives an image of an asset
 * and returns field-filling suggestions (name, category, description, etc.)
 * generated by a computer vision model.</p>
 */
@RestController
@RequestMapping("/api/v0/ia/cadastro-foto")
public class CadastroFotoIaController {

    private final CadastroFotoIaService service;

    /**
     * Constructs the controller injecting the photo registration service.
     *
     * @param service service responsible for image analysis and suggestion generation
     */
    public CadastroFotoIaController(CadastroFotoIaService service) {
        this.service = service;
    }

    /**
     * Analyses an image of an asset and returns registration field-filling suggestions.
     *
     * @param arquivo item image uploaded by the client
     * @return {@code 200 OK} with name, category, description and other field suggestions
     */
    @PostMapping(value = "/sugestoes", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public ResponseEntity<CadastroFotoSugestaoResponseDTO> sugerirCadastro(@RequestParam("arquivo") MultipartFile arquivo) {
        return ResponseEntity.ok(service.sugerirCadastro(arquivo));
    }
}
