package br.com.stella.api.entity;

import br.com.munif.common.persistencia.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.envers.Audited;

/**
 * Entity representing a main item in the inventory.
 *
 * <p>The main item is the "model" or "type" of a physical asset — for example,
 * "Dell Inspiron 15 Laptop". Each main item can have multiple
 * {@link ItemInstance physical instances} associated with it, each with its own
 * serial number, asset tag, and location.</p>
 *
 * <p>The item may have an image stored in an object storage service (e.g.: S3).
 * The fields {@code imageBucket}, {@code imageObjectKey} and other image metadata
 * allow retrieving and displaying that image.</p>
 *
 * <p>This entity is audited by Hibernate Envers: all changes are recorded
 * in the {@code item_mestre_aud} table.</p>
 */
@Entity
@Audited
@Table(name = "item_mestre")
@Getter
@Setter
@NoArgsConstructor
public class MainItem extends BaseEntity {

    /**
     * Name of the main item. Required, up to 150 characters.
     * Example: {@code "Dell Inspiron 15 Laptop"}.
     */
    @Column(name = "nome", nullable = false, length = 150)
    private String name;

    /**
     * Detailed description of the item, containing relevant characteristics.
     * Optional, up to 500 characters.
     */
    @Column(name = "descricao", length = 500)
    private String description;

    /**
     * Internal notes about the item (maintenance history, usage restrictions, etc.).
     * Optional, up to 1000 characters.
     */
    @Column(name = "observacoes", length = 1000)
    private String notes;

    /**
     * Indicates the registration origin of the item (e.g.: {@code "MANUAL"}, {@code "IA"}, {@code "FOTO"}).
     * Used to track how the item was entered into the system.
     * Up to 50 characters.
     */
    @Column(name = "origem_cadastro", length = 50)
    private String registrationOrigin;

    /**
     * Name of the bucket in the object storage service where the item's image is stored.
     * {@code null} when the item has no registered image.
     * Up to 100 characters.
     */
    @Column(name = "imagem_bucket", length = 100)
    private String imageBucket;

    /**
     * Key (path/object name) of the image within the object storage bucket.
     * Used together with {@link #imageBucket} to locate the file.
     * Up to 500 characters.
     */
    @Column(name = "imagem_object_key", length = 500)
    private String imageObjectKey;

    /**
     * MIME type of the stored image (e.g.: {@code "image/jpeg"}, {@code "image/png"}).
     * Required to serve the file with the correct {@code Content-Type} header.
     * Up to 100 characters.
     */
    @Column(name = "imagem_content_type", length = 100)
    private String imageContentType;

    /**
     * Size of the image in bytes. Useful for displaying information to the user
     * and for storage quota checks.
     */
    @Column(name = "imagem_tamanho_bytes")
    private Long imageSizeBytes;

    /**
     * Indicates whether the image was generated by artificial intelligence.
     * {@code true} when the image was produced by an AI model;
     * {@code false} when it was manually uploaded by the user.
     */
    @Column(name = "imagem_generated_by_ai", nullable = false)
    private boolean imageGeneratedByAi;

    /**
     * Identifier of the AI provider that generated the image (e.g.: {@code "openai"}, {@code "anthropic"}).
     * {@code null} when {@link #imageGeneratedByAi} is {@code false}.
     * Up to 50 characters.
     */
    @Column(name = "imagem_provider", length = 50)
    private String imageProvider;

    /**
     * Category to which this item belongs.
     * Optional relationship: an item may exist without a defined category.
     * Loaded lazily to avoid unnecessary joins.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria_id")
    private Category category;
}
