package br.com.munif.comum.dto;

import java.time.Instant;

/**
 * Generic DTO representing an audited revision of an entity.
 *
 * <p>Used to expose the change history tracked by Hibernate Envers.
 * Each instance corresponds to a version of the entity at a specific point in time.
 * The type parameter {@code T} must be the full response DTO of the audited entity.</p>
 *
 * <p>Usage example: {@code RevisaoDTO<PessoaResponseDTO>} for the change history
 * of a {@code Pessoa}.</p>
 *
 * @param <T>      response DTO type of the audited entity
 * @param revisao  sequential revision number generated by Hibernate Envers
 * @param dataHora date and time when the revision was created (UTC)
 * @param entidade snapshot of the entity data at this revision, represented as a DTO
 */
public record RevisaoDTO<T>(
        Number revisao,
        Instant dataHora,
        T entidade
) {
}
